#Server Configuration
server:  
  port: 8080 
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8  
  context-path: /enroll
  
#Logback Configuration
logging:
  config: classpath:logback.xml
  debug: true

#Spring Configuration
spring:
  datasource:  
    url: jdbc:mysql://localhost:3306/enroll  
    username: root  
    password: root
    driverClassName: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial: 10
  jpa:  
    database: MYSQL  
    show-sql: true
    hibernate:  
      ddl-auto: update
      format-sql: true  
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy  
    properties:  
      hibernate:  
        dialect: org.hibernate.dialect.MySQLDialect
        #dialect: org.hibernate.dialect.MySQL5Dialect 